"""adds repr method to Expense table

Revision ID: 9756042ca240
Revises: 8f46ee218453
Create Date: 2023-08-11 12:39:12.480097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9756042ca240'
down_revision = '8f46ee218453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
