"""changed date column data type

Revision ID: aa9077976f78
Revises: e60322682ce9
Create Date: 2023-08-12 06:53:09.134452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9077976f78'
down_revision = 'e60322682ce9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'date')    
    op.add_column('expenses', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'date')
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
